[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/mmcdole/gofeed"
  version = "1.0.0-beta"

[[constraint]]
  name = "github.com/tucnak/telebot"
  version = "1.0.0"
